### ISSUE TITLE
Req: Improve the file name parsing

### ISSUE THREAD

**Issue by SasikumarN** [tympanix/supper#50]
When the file name is with website name it failed to detect the movie. otherwise, it detects well (tested only  20 mins).

Also please add some documentation on how to use it, what is the config file, it's format and supported naming schemes.

I feel a bit difficult when I downloaded tar binaries. I didn't find the config file in it. I was searching the source code for it. Somehow I figured and installed Debian package and found it's working.

I want to appreciate your effort on this. Thanks, dev! (Yes, I used filebot and I always feel it weird.). I feel this project matured enough to try.

**Comment by tympanix** [comment]
Glad you found it useful. It is true that the tar binary does not come with the config, nor is the binary able to generate one for you (which could be an improvement). Could you supply an example of how such a filename would include a website link? Documentation is lacking - that's true. I will improve on this matter per your request.

**Comment by SasikumarN** [comment]
Normally downloading a movie from torrent  will have the following format. ;)

www.URL.com - [Movie Name] - [May be Year]-[Video Audio details here].extension

I found [this](https://github.com/guessit-io/guessit) one did well on my quick test. Could be helpful for implementing it here.
